name: hear_and_see_safe
description: A Flutter app for children with visual and hearing impairments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Accessibility & Audio
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  vibration: ^3.1.6
  flutter_compass: ^0.8.1
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  http: ^1.2.2
  google_mlkit_image_labeling: ^0.13.0
  image: ^4.2.0
  
  # State Management
  provider: ^6.1.1
  
  # Localization
  intl: ^0.20.2
  easy_localization: ^3.0.3
  
  # Utilities
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  record: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/home/mk/
    - assets/audio/home/en/
    - assets/audio/home/sq/
    - assets/audio/braille/mk/
    - assets/audio/braille/en/
    - assets/audio/braille/sq/
    - assets/audio/melody_memory/mk/
    - assets/audio/melody_memory/en/
    - assets/audio/melody_memory/sq/
    - assets/audio/rhythm_tap/mk/
    - assets/audio/rhythm_tap/en/
    - assets/audio/rhythm_tap/sq/
    - assets/audio/sound_identification/mk/
    - assets/audio/sound_identification/en/
    - assets/audio/sound_identification/sq/
    - assets/audio/spatial_orientation/mk/
    - assets/audio/spatial_orientation/en/
    - assets/audio/spatial_orientation/sq/
    - assets/sounds/pong/
    - assets/sounds/rhythm/
    - assets/sounds/melody_memory/
    - assets/sounds/sound_identification/
    - assets/sounds/picture_book/
    - assets/audio/sound_memory/mk/
    - assets/audio/sound_memory/en/
    - assets/audio/sound_memory/sq/
    - assets/audio/voice_pong/mk/
    - assets/audio/voice_pong/en/
    - assets/audio/voice_pong/sq/
    - assets/audio/story_choices/mk/
    - assets/audio/story_choices/en/
    - assets/audio/story_choices/sq/
    - assets/audio/picture_book/mk/
    - assets/audio/picture_book/en/
    - assets/audio/picture_book/sq/
    - assets/audio/language/mk/
    - assets/audio/language/en/
    - assets/audio/language/sq/
    - assets/audio/number_games/mk/
    - assets/audio/number_games/en/
    - assets/audio/number_games/sq/
    - assets/audio/cyber_safety/mk/
    - assets/audio/cyber_safety/en/
    - assets/audio/cyber_safety/sq/
    - assets/audio/language/
    - assets/audio/voice/mk/
    - assets/audio/voice/en/
    - assets/audio/voice/sq/
    - assets/audio/settings/mk/
    - assets/audio/settings/en/
    - assets/audio/settings/sq/
    - assets/audio/camera/mk/
    - assets/audio/camera/en/
    - assets/audio/camera/sq/
    - assets/sounds/
    - assets/models/
    - assets/translations/
    - assets/translations/en-US.json
    - assets/translations/mk-MK.json
    - assets/translations/sq-AL.json
  
#  fonts:
#   - family: Accessibility
#      fonts:
#       - asset: assets/fonts/Accessibility-Regular.ttf

# Иконата на апликацијата. По промена на сликите изврши:
#   dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 26
  adaptive_icon_background: "#1C1A63"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#14134A"
    theme_color: "#14134A"